= Prioritized To Do List

== Prioritized List
* Migrate from Hubitat 2.3.5.152 to 2.3.6.135 (or latest).
* Fix Manual Override

** Manual Override *DOES NOT* detect room button presses consistently.
** The current strategy is to watch the LED on an associated Keypad.
** Some room scenes DO NOT have an associated keypad button.
** Watching a Main Repeater LED is an improvement, but only works if the
for the portion of a scene (if any) that depends on a Main Repeater.
** For independent devices, it may be necessary to identify departures in expected on()/off()/level()!

* Un-setting Manual Override *IS NOT* sufficient for ALL_AUTO as it does not displace room scenes - i.e., activate VSW AUTOMATIC per room.

== On Deck
.`whaRoom`
* Add all motion-based Rooms

== Explore `TileManager` for (per room):
* Scene / Scene-Change visibility in one tile (similar to a mode tile).
* Repeater per scene button numbers.
* Per independent device scene level numbers.

== Create `LuxHysteresisApp`
Each instance of the prospective *LuxHysterisApp* application would:

* Create and manage a Virtual Switch (device).
** where `on` denotes above Lux threshold.
** where `off` denotes at or below Lux threshold.
* Consume data from real-time illuminance devices.
** Allow for `all` or `any` net-device behavior. +
_Example: Any above level vs All above level._
** Establish the target Lux level(s) for setting switch state.
** Establish the duration requirement(s) for state transitions. +
_Example: Above level for `t`, Below level for `t`._

.Draft Model
[horizontal]
`settings.sensors`:: Participating illuminance sensors
`settings.nettingEnabled`:: If `true` all sensors must meet criteria +
If `false` any sensor can satisfy criteria
`settings.onDurationMinutes`:: The time `t` in minutes that criteria must
be present to enable switch.
`settings.offDurationMinutes`:: The time `t` in minutes that criteria must
not be present to disable switch.
`vsw.on`:: Lux-level is above threshold for the required duration.
`vsw.off`:: Lux-level is below threshold for the required duration.

=== Prospective `whaRoom` changes for `LuxHysteresisApp`
* A `room` can optionally depend on a device managed by a `LuxHysteresisApp`
device instance for light-level activation.
* A prospective `luxHandler()` will behave similarly to `void motionSensorHandler (Event e)`.

== Implement `wha` Low Priority
.See `specialFnHandler()

.Group 1
For *MANUAL OVERRIDE* compatibility, the following need (a) an optional per room custom scene, *OR* (b) a new whole-house hubitat mode.

* `ALL_OFF`
* `ALL_ON`
* `CLEANING`

.Group 2
If the away/vacation program leverages optional per-room scenes, then the
overall approach will be compatible as a whole-house mode *OR* per-room
custom scenes.

* `AWAY`

.Group 3
The specific behavior of the following is TBD. The solution needs to be
compatible with modes, MANUAL OVERRIDE detection, etc.

* `ALARM`
* `PANIC`
* `FLASH`

.Group 4
The following is intended to silence door alarms, etc.

* `QUIET`

== RELEASED
.`whaRoom`
&#x2713; Replace `state.MANUAL_OVERRIDE` with child device `VswManualOverride`.

.`wha`
&#x2713; Implement `ALL_AUTO` in `void specialFnHandler (Event e)`.

