= Prioritized To Do List

== High Priority
.`whaRoom`
** Replace `state.MANUAL_OVERRIDE` with child device `VswManualOverride`.

.`wha`
* Implement `ALL_AUTO` in `void specialFnHandler (Event e)`.

.`whaRoom`
* Add all motion-based Rooms

== Explore `TileManager` for (per room):
* Scene / Scene-Change visibility in one tile (similar to a mode tile).
* Repeater per scene button numbers.
* Per independent device scene level numbers.

== Create `LuxHysteresisApp`
Each instance of the prospective *LuxHysterisApp* application would:

* Create and manage a Virtual Switch (device).
** where `on` denotes above Lux threshold.
** where `off` denotes at or below Lux threshold.
* Consume data from real-time illuminance devices.
** Allow for `all` or `any` net-device behavior. +
_Example: Any above level vs All above level._
** Establish the target Lux level(s) for setting switch state.
** Establish the duration requirement(s) for state transitions. +
_Example: Above level for `t`, Below level for `t`._

.Draft Model
[horizontal]
`settings.sensors`:: Participating illuminance sensors
`settings.nettingEnabled`:: If `true` all sensors must meet criteria +
If `false` any sensor can satisfy criteria
`settings.onDurationMinutes`:: The time `t` in minutes that criteria must
be present to enable switch.
`settings.offDurationMinutes`:: The time `t` in minutes that criteria must
not be present to disable switch.
`vsw.on`:: Lux-level is above threshold for the required duration.
`vsw.off`:: Lux-level is below threshold for the required duration.

=== Prospective `whaRoom` changes for `LuxHysteresisApp`
* A `room` can optionally depend on a device managed by a `LuxHysteresisApp`
device instance for light-level activation.
* A prospective `luxHandler()` will behave similarly to `void motionSensorHandler (Event e)`.

== Implement `wha` Low Priority
.In `void specialFnHandler (Event e)`:
* `ALL_OFF`
* `ALARM`
* `ALL_ON`
* `AWAY`
* `CLEANING`
* `FLASH`
* `PANIC`
* `QUIET`
